# Generated by Django 4.2.22 on 2025-06-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
